name: Go PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: |
          go test ./... -v -race

      - name: Install Linters
        run: | 
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Linters
        run: |
          golanci-lint run ./...
          staticcheck ./...


